In [148]:
import pandas as pd
import numpy as np

pd.__version__

'2.3.0'

In [149]:
df = pd.read_csv('car_fuel_efficiency.csv')

In [150]:
df.head(2)

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217

In [151]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9704 entries, 0 to 9703
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   engine_displacement  9704 non-null   int64  
 1   num_cylinders        9222 non-null   float64
 2   horsepower           8996 non-null   float64
 3   vehicle_weight       9704 non-null   float64
 4   acceleration         8774 non-null   float64
 5   model_year           9704 non-null   int64  
 6   origin               9704 non-null   object 
 7   fuel_type            9704 non-null   object 
 8   drivetrain           9704 non-null   object 
 9   num_doors            9202 non-null   float64
 10  fuel_efficiency_mpg  9704 non-null   float64
dtypes: float64(6), int64(2), object(3)
memory usage: 834.1+ KB


#### Count Columns Missing values

In [152]:
df.isnull().any().sum()

np.int64(4)

#### Unique fuel types

In [153]:
df['fuel_type'].nunique()

2

#### Max Fuel Efficiency Asia

In [154]:
df["origin"].value_counts()

origin
Europe    3254
Asia      3247
USA       3203
Name: count, dtype: int64

In [155]:
asia = df[df["origin"] == "Asia"]

In [156]:
asia.head(2)

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                   250            1.0       174.0     2714.219310   
12                  320            5.0       145.0     2783.868974   

    acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8           10.3        2016   Asia    Diesel  Front-wheel drive       -1.0   
12          15.1        2010   Asia    Diesel    All-wheel drive        1.0   

    fuel_efficiency_mpg  
8             16.823554  
12            16.175820

In [157]:
asia['fuel_efficiency_mpg'].max()

np.float64(23.759122836520497)

#### Horsepower 

In [158]:
median_before = df["horsepower"].median() 

median_before


np.float64(149.0)

In [159]:
mode = df["horsepower"].mode()[0]

mode

np.float64(152.0)

In [160]:
df["horsepower"] = df["horsepower"].fillna(mode)

In [161]:
median_after = df["horsepower"].median()

In [162]:
median_before, median_after, mode

(np.float64(149.0), np.float64(152.0), np.float64(152.0))

## Sum of weights

In [163]:
asia.head(2)

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                   250            1.0       174.0     2714.219310   
12                  320            5.0       145.0     2783.868974   

    acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8           10.3        2016   Asia    Diesel  Front-wheel drive       -1.0   
12          15.1        2010   Asia    Diesel    All-wheel drive        1.0   

    fuel_efficiency_mpg  
8             16.823554  
12            16.175820

In [164]:
asia_subset = asia[['model_year', 'vehicle_weight']]
asia_subset.head(7)

model_year  vehicle_weight
8         2016     2714.219310
12        2010     2783.868974
14        2007     3582.687368
20        2011     2231.808142
21        2016     2659.431451
34        2014     2844.227534
38        2019     3761.994038

In [165]:
x = asia_subset.head(7)

In [166]:
X = np.array(x)

In [167]:
X

array([[2016.        , 2714.21930965],
       [2010.        , 2783.86897424],
       [2007.        , 3582.68736772],
       [2011.        , 2231.8081416 ],
       [2016.        , 2659.43145076],
       [2014.        , 2844.22753389],
       [2019.        , 3761.99403819]])

#### Transpose of X

In [183]:
XT = X.T

#### Transpose of X times X

In [184]:
XTX = XT @ X  

In [185]:
XTX

array([[28373339.        , 41431216.5073268 ],
       [41431216.5073268 , 62248334.33150762]])

In [186]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 1.25380877e-06, -8.34509443e-07],
       [-8.34509443e-07,  5.71497081e-07]])

In [187]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [188]:
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [191]:
w = XTX_inv @ TX @ y

In [192]:
w

array([0.5049067 , 0.01386421])

In [193]:
result = w.sum()

In [194]:
result

np.float64(0.5187709081074054)